# Generated by Django 4.1.3 on 2022-11-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayMaster',
        ),
    ]
