# Generated by Django 4.1.3 on 2022-11-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_delete_daymaster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='subject_name',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='name',
            new_name='tutor_name',
        ),
    ]
