# Generated by Django 4.1.3 on 2022-11-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_group_group_num_alter_subject_subject_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_num',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_name',
            field=models.CharField(max_length=150),
        ),
    ]
