# Generated by Django 4.1.3 on 2022-11-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_alter_classroom_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONtimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
