# Generated by Django 4.1.3 on 2022-11-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_jsontimetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsontimetable',
            name='date_time_of_upload',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
