# Generated by Django 4.1.3 on 2022-12-01 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_jsontimetable_date_time_of_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('work_type',),
            },
        ),
        migrations.AlterField(
            model_name='timetable',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.worktype'),
        ),
    ]
