# Generated by Django 4.1.3 on 2022-12-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_worktype_alter_timetable_work_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='work_type',
        ),
    ]
