# Generated by Django 4.1.3 on 2022-12-01 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_remove_timetable_work_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkType',
        ),
    ]
