# Generated by Django 4.1.3 on 2022-12-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_remove_timetable_work_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkType',
        ),
        migrations.AddField(
            model_name='timetable',
            name='work_type',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
