# Generated by Django 4.1.3 on 2022-12-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_worktype_alter_timetable_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='work_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='work_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='work_start',
            field=models.TimeField(),
        ),
    ]
